### PR TITLE
Fix how we handle file errors

### LINKED ISSUE #75: FileManager.zipFilesInternal: FileErrorException
```ruby
Exception org.onionshare.android.files.FileErrorException:
  at org.onionshare.android.files.FileManager.zipFilesInternal (FileManager.kt:156)
```

### PR DESCRIPTION
**Pull request by grote**
When introducing parallel zipping and starting of Tor, we've broken the handling of file errors. The new state handling also complicates this. There were a couple of issues that are hopefully fixed by this MR.

Fixes #75

### CODE REVIEW

File: app/src/main/java/org/onionshare/android/ShareManager.kt [hunk 1]
```diff
@@ -59,8 +59,12 @@ class ShareManager @Inject constructor(
         if (f is FilesState.Added && t is TorState.Stopped && w is WebServerState.Stopped && !w.downloadComplete) {
             if (f.files.isEmpty()) emit(ShareUiState.NoFiles)
             else emit(ShareUiState.FilesAdded(f.files))
-        } // handle error while adding files
-        else if (f is FilesState.Error) {
+        } // handle error while adding files while Tor is still starting or started
+        else if (f is FilesState.Error && (t is TorState.Starting || t is TorState.Started)) {
+            stopSharing()
```
Comment (grote) [inline app/src/main/java/org/onionshare/android/ShareManager.kt:64]: If we don't stop, Tor would keep running and not match the UI.

File: app/src/main/java/org/onionshare/android/ShareManager.kt [hunk 2]
```diff
@@ -125,6 +129,8 @@ class ShareManager @Inject constructor(
             // TODO check if this always works as expected
             startSharingJob?.cancelAndJoin()
         }
+        // the ErrorAddingFile state is transient and needs manual reset to not persist
+        if (shareState.value is ShareUiState.ErrorAddingFile) fileManager.resetError()
```
Comment (grote) [inline app/src/main/java/org/onionshare/android/ShareManager.kt:133]: We have to leave the error state somehow. As our sharing state depends on the managers and `shouldStop`, we need to modify the state of one of the managers for this. Otherwise, changing `shouldStop` in the next line emits a new state keeping us in an error state.

File: app/src/main/java/org/onionshare/android/files/FileManager.kt [hunk 3]
```diff
@@ -113,15 +113,16 @@ class FileManager @Inject constructor(
...
-            zipJob = launch { zipFilesInternal() }
-        } catch (e: FileErrorException) {
-            // remove errorFile from list of files, so user can try again
-            val newFiles = state.value.files.toMutableList().apply { remove(e.file) }
-            _state.value = FilesState.Error(newFiles, e.file)
-        } catch (e: IOException) {
-            _state.value = FilesState.Error(state.value.files)
+        zipJob = launch {
+            try {
+                zipFilesInternal()
```
Comment (grote) [inline app/src/main/java/org/onionshare/android/files/FileManager.kt:118]: That's the main issue that showed as a crash: When launching a new coroutine in the current coroutine context, the exception thrown in there would bubble up to the parent context, so our try/catch wasn't actually catching it :facepalm:

File: app/src/main/java/org/onionshare/android/files/FileManager.kt [hunk 4]
```diff
@@ -195,7 +194,16 @@ class FileManager @Inject constructor(
         val currentState = state.value
         if (currentState is Zipping) currentState.zip.delete()
         if (currentState is Zipped) currentState.sendPage.zipFile.delete()
-        _state.value = Added(currentState.files)
+        _state.value = if (currentState is FilesState.Error) {
+            FilesState.Error(currentState.files, currentState.errorFile)
+        } else {
+            Added(currentState.files)
```
Comment (grote) [inline app/src/main/java/org/onionshare/android/files/FileManager.kt:200]: When stopping sharing after an error, this would clean our error state too quickly for showing something in the UI.

File: app/src/main/java/org/onionshare/android/ShareManager.kt [hunk 5]
```diff
@@ -59,8 +59,12 @@ class ShareManager @Inject constructor(
         if (f is FilesState.Added && t is TorState.Stopped && w is WebServerState.Stopped && !w.downloadComplete) {
             if (f.files.isEmpty()) emit(ShareUiState.NoFiles)
             else emit(ShareUiState.FilesAdded(f.files))
-        } // handle error while adding files
-        else if (f is FilesState.Error) {
+        } // handle error while adding files while Tor is still starting or started
+        else if (f is FilesState.Error && (t is TorState.Starting || t is TorState.Started)) {
+            stopSharing()
+        } // handle error while adding files when Tor has stopped
+        else if (f is FilesState.Error && t is TorState.Stopped) {
```
[the remark this answers is not in the document]
Comment (grote) [reply app/src/main/java/org/onionshare/android/ShareManager.kt:66]: The reason I didn't include Stopping is that I want to be sure Tor has stopped, before I let the user try again.

In your scenario, even if we don't cancel the file manager before, waiting for stopped before showing the file error seems alright? If the cancel should have priority, we should check how that would behave.

File: app/src/main/java/org/onionshare/android/ShareManager.kt (hunk 1 above)
Comment (grote) [reply app/src/main/java/org/onionshare/android/ShareManager.kt:64]: The error will be shown as soon as Tor has stopped as we don't reset the error state before.

File: app/src/main/java/org/onionshare/android/ShareManager.kt (hunk 2 above)
Comment (grote) [reply app/src/main/java/org/onionshare/android/ShareManager.kt:133]: The comment meant to say that the error state should be transient, but that doesn't magically happen, so we need to reset it manually for transient behavior.

File: app/src/main/java/org/onionshare/android/ShareManager.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (akwizgran) [reply app/src/main/java/org/onionshare/android/ShareManager.kt:66]: Sounds good, thanks for explaining.

**Review by akwizgran — APPROVED** [review]
